#!/usr/bin/env node
// tools/attract.cjs : writes the attract tape into the game and the attract film.
//
//   node tools/attract.cjs            write src/game/21-attract.js and the attract block of src/timeline.js
//   node tools/attract.cjs --check    write nothing; exit 1 when either file is out of date
//
// The tape is tools/proof/tapes/<CONFIG.firstLevel>.modern.json (recorded by tools/proof/levels.cjs
// --replan). FILM.game.record replays it on the engine for its fingerprint, which must equal the tape's
// own. 21-attract.js gets GAME.ATTRACT = { length, fp, rle, feel }; src/timeline.js gets the tape's length,
// the frame its level song starts, that song's id and CONFIG.title as the closing caption. A second run
// with nothing changed rewrites nothing.
'use strict';

const fs = require('fs');
const path = require('path');
const H = require('./proof/harness.cjs');

const ROOT = path.resolve(__dirname, '..');
const ATTRACT_JS = path.join(ROOT, 'src', 'game', '21-attract.js');
const TIMELINE_JS = path.join(ROOT, 'src', 'timeline.js');
const check = process.argv.includes('--check');

function fail(msg) {
  console.log(`FAIL attract.cjs: ${msg}`);
  process.exit(1);
}

const G = H.load();
const GAME = G.GAME;
const first = GAME.CONFIG.firstLevel;
const tapeFile = path.join(__dirname, 'proof', 'tapes', `${first}.modern.json`);
if (!fs.existsSync(tapeFile)) fail(`no ${path.relative(ROOT, tapeFile)}: run node tools/proof/levels.cjs --replan`);
const tape = JSON.parse(fs.readFileSync(tapeFile, 'utf8'));
const bytes = G.decode(tape.rle);
if (!bytes || bytes.length !== tape.frames) fail(`${path.basename(tapeFile)} decodes to ${bytes ? bytes.length : 'nothing'} frames, not ${tape.frames}`);
if (tape.opts && tape.opts.start && tape.opts.start !== first) fail(`${path.basename(tapeFile)} starts at ${tape.opts.start}, CONFIG.firstLevel is ${first}`);

const rec = G.FILM.game.record(bytes, bytes.length, 'modern');
if (rec.fp !== tape.fp) fail(`the engine replays the tape to fingerprint ${rec.fp}, the tape says ${tape.fp}: re-record it`);
if (rec.rle !== tape.rle) fail('the recorded RLE differs from the tape RLE');

// the frame the first level's song starts on the tape
const W = GAME.newWorld({ start: first, feel: 'modern' });
const song = GAME.GAME_DEFS[first].song;
let songAt = -1;
for (let f = 0; f < bytes.length && songAt < 0; f++) {
  for (const e of GAME.step(W, bytes[f])) if (e.type === 'song' && e.id === song && songAt < 0) songAt = f;
}
if (songAt < 0) fail(`the tape never starts the level song '${song}'`);

const attractJs =
  `// game/21-attract.js : generated by tools/attract.cjs, do not edit. GAME.ATTRACT is { length, fp, rle, feel } or null.\n` +
  `// Source: tools/proof/tapes/${first}.modern.json (${tape.meta && tape.meta.what ? tape.meta.what : first}).\n` +
  `(function () {\n  'use strict';\n  const FILM = (window.FILM = window.FILM || {});\n  const GAME = (FILM.__game = FILM.__game || {});\n` +
  `  GAME.ATTRACT = ${JSON.stringify({ length: rec.length, fp: rec.fp, rle: rec.rle, feel: rec.feel })};\n})();\n`;

const tl0 = fs.existsSync(TIMELINE_JS) ? fs.readFileSync(TIMELINE_JS, 'utf8') : null;
if (tl0 == null) fail('src/timeline.js is missing');
const re = /(\/\/ <attract>[^\n]*\n)[\s\S]*?(\n\s*\/\/ <\/attract>)/;
if (!re.test(tl0)) fail('src/timeline.js has no // <attract> ... // </attract> block');
const block = `  const ATTRACT = { tape: ${rec.length}, songAt: ${songAt}, song: ${JSON.stringify(song)}, caption: ${JSON.stringify(GAME.CONFIG.title || '')} };`;
const tl1 = tl0.replace(re, `$1${block}$2`);

const a0 = fs.existsSync(ATTRACT_JS) ? fs.readFileSync(ATTRACT_JS, 'utf8') : '';
const stale = [];
if (a0 !== attractJs) stale.push('src/game/21-attract.js');
if (tl0 !== tl1) stale.push('src/timeline.js');
if (check) {
  if (stale.length) fail(`out of date: ${stale.join(', ')} (run node tools/attract.cjs)`);
} else {
  if (a0 !== attractJs) fs.writeFileSync(ATTRACT_JS, attractJs);
  if (tl0 !== tl1) fs.writeFileSync(TIMELINE_JS, tl1);
}
console.log(`PASS attract.cjs: ${first}.modern, ${rec.length} frames, fp ${rec.fp}, song '${song}' at frame ${songAt}; ${check ? 'checked' : stale.length ? 'wrote ' + stale.join(', ') : 'nothing to write'}`);
