// src/sprites.js : the game's cast, original art for every name in src/manifest.js. Owner: art.
//
// Format: FILM.retro.SPRITES_DEF[name] = { l, r } (or { legends, r }); see templates/sprites.js and
// templates/art-bible-retro.md. Characters (hero_*, foe_*, and the palette-swapped item_power and
// item_fragment_*) key their pixels by the slots '1' '2' '3' and take their legend from FILM.retro.SPAL;
// everything else keys a legend of named RETRO_PAL colours. At most 3 colours plus transparent a map.
//
// The cast: BIT, a round robot with an antenna and a cyan visor (small 16x16, big 24x24, a 20x20 grow
// drawing); a walking hex nut; a battery power-up; spinning chip coins; a gear token; a lamp-post
// checkpoint; a radio beacon tower with a bolt banner and a tin radio hut as the goal; data crates for the
// ? blocks; steel conduit pipes; terraced mesas, cloud puffs and shrubs as scenery. Nothing here is traced
// from, or shaped after, any published game's sprites.
//
// Shapes that are geometry (coins, token, scenery, pipes, house, fireworks) are generated by the small
// helpers below; the characters are drawn by hand.
(function () {
  'use strict';
  const R = FILM.retro;
  const C = R.C;
  Object.assign(R.RETRO_PAL, {
    ink: C(0x0f), // $0F black: outlines
    hudWhite: C(0x30), // $30 HUD and card text (required)
    steel: C(0x10), // $10 the robot's body, the beacon tower
    shadow: C(0x00), // $00 grey
    visor: C(0x2c), // $2C cyan: the visor, the token
    red: C(0x16), // $16 the beacon lamp, the X eyes
    moss: C(0x1a), // $1A grass, shrubs
    lime: C(0x29), // $29 battery, shrub highlight
    dirt: C(0x17), // $17 soil
    clay: C(0x27), // $27 bricks, the hut walls
    rust: C(0x07), // $07 brick mortar, the hut roof
    gold: C(0x28), // $28 coins, crates
    amber: C(0x38), // $38 coin shine
    violet: C(0x13), // $13 the nut
    sky: C(0x22), // $22 the overworld backdrop (30-draw.js BACKDROP)
    cloud: C(0x31), // $31 cloud shade
    teal: C(0x1c), // $1C conduit pipes
    pale: C(0x3c), // $3C conduit shine
    deep: C(0x0c), // $0C conduit shade, underground outline
    mesa: C(0x1b), // $1B mesa body
    mesaLit: C(0x2b), // $2B mesa ledge
    blue: C(0x21), // $21 the nut underground
    pink: C(0x24), // $24 the nut underground
  });
  const P = R.RETRO_PAL;
  const SP = R.SPRITES_DEF;

  // ---------------------------------------------------------------- helpers
  const rev = (s) => s.split('').reverse().join('');
  const mirror = (halves) => halves.map((h) => h + rev(h));
  // a map from a function of (x, y) -> key or '.'
  function gen(w, h, fn) {
    const rows = [];
    for (let y = 0; y < h; y++) {
      let r = '';
      for (let x = 0; x < w; x++) r += fn(x, y) || '.';
      rows.push(r);
    }
    return rows;
  }
  // fill a shape (inside(x, y) -> fill key or null) and outline every filled pixel that touches the outside
  function shape(w, h, inside, edge) {
    const at = (x, y) => (x < 0 || y < 0 || x >= w || y >= h ? null : inside(x, y));
    return gen(w, h, (x, y) => {
      const k = at(x, y);
      if (!k) return '.';
      if (edge && (!at(x - 1, y) || !at(x + 1, y) || !at(x, y - 1) || !at(x, y + 1))) return edge;
      return k;
    });
  }
  const flipH = (rows) => rows.map(rev);

  // ---------------------------------------------------------------- palettes (slots 1 outline, 2 body, 3 light)
  R.SPAL.hero = Object.freeze([P.ink, P.steel, P.visor]);
  R.SPAL.foe = Object.freeze([P.ink, P.violet, P.hudWhite]);
  R.SPAL.foeU = Object.freeze([P.blue, P.pink, P.hudWhite]); // the nut underground: no black outline on black
  R.SPAL.power = Object.freeze([P.ink, P.lime, P.hudWhite]); // the battery
  R.SPAL.life = Object.freeze([P.ink, P.red, P.hudWhite]); // the 1UP: the battery in red
  R.SPAL.fragment = Object.freeze([P.rust, P.clay, P.amber]);
  R.SPAL.fragmentU = Object.freeze([P.deep, P.teal, P.pale]);
  const heroL = R.slots(R.SPAL.hero);
  const foeL = R.slots(R.SPAL.foe);

  // ---------------------------------------------------------------- BIT, small (16x16)
  const body = [
    '......1331......',
    '.......11.......',
    '.....111111.....',
    '...1122222211...',
    '..122222222221..',
    '.12211111111221.',
    '.12211113311221.',
    '.12211113311221.',
    '.12211111111221.',
    '1122222222222211',
    '1122222222222211',
    '..122222222221..',
    '...1122222211...',
  ];
  const blinkBody = body.slice();
  blinkBody[6] = '.12211111111221.';
  const deadBody = body.slice();
  deadBody[6] = '.12211131311221.';
  deadBody[7] = '.12211113111221.';
  const legs = {
    idle: ['.....11..11.....', '.....11..11.....', '....111..111....'],
    run1: ['....11....11....', '...11......11...', '..111.......111.'],
    run2: ['.....11..11.....', '......1111......', '.....111.111....'],
    run3: ['......11.11.....', '.....11...11....', '....111...111...'],
    jump: ['...111....111...', '..111......111..', '................'],
    skid: ['......11...11...', '.......11...11..', '.......111..111.'],
    pole1: ['......1111......', '.......11.......', '......111.......'],
    pole2: ['.......1111.....', '........11......', '.......111......'],
    dead: ['...11......11...', '..11........11..', '................'],
  };
  for (const pose of ['idle', 'run1', 'run2', 'run3', 'jump', 'skid', 'pole1', 'pole2']) SP['hero_small_' + pose] = { l: heroL, r: body.concat(legs[pose]) };
  SP.hero_small_blink = { l: heroL, r: blinkBody.concat(legs.idle) };
  SP.hero_small_dead = { l: heroL, r: deadBody.concat(legs.dead) };

  // ---------------------------------------------------------------- BIT, growing (20x20)
  const mid = mirror([
    '........13',
    '.........1',
    '......1111',
    '....112222',
    '...1222222',
    '..12211111',
    '..12213333',
    '..12211111',
    '.122222222',
    '.122222222',
    '.122221111',
    '.122221331',
    '.122221111',
    '..12222222',
    '...1122222',
    '.....11111',
  ]).concat(['......111..111......', '......121..121......', '.....1221..1221.....', '.....1111..1111.....']);
  SP.hero_grow_mid = { l: heroL, r: mid };

  // ---------------------------------------------------------------- BIT, big (24x24)
  const bigTop = [
    '..........13',
    '...........1',
    '.......11111',
    '.....1122222',
    '....12222222',
    '...122111111',
    '...122133333',
    '...122133333',
    '...122111111',
    '...122222222',
    '..1122222222',
    '.12222222222',
    '.12222211111',
    '.12222213311',
    '.12222211111',
    '.12222222222',
    '..1222222222',
    '...112222222',
    '.....1111111',
  ];
  const bigBody = mirror(bigTop);
  const bigBlink = bigBody.slice();
  bigBlink[6] = mirror(['...122111111'])[0];
  const bigLegs = {
    idle: ['.......111....111.......', '.......121....121.......', '.......121....121.......', '......1221....1221......', '......1111....1111......'],
    run1: ['......111......111......', '.....121........121.....', '....121..........121....', '...1221..........1221...', '...1111..........1111...'],
    run2: ['.........111111.........', '.........121121.........', '........1221.121........', '.......1221...1221......', '.......1111...1111......'],
    run3: ['.......111....111.......', '......121......121......', '.....121........121.....', '....1221........1221....', '....1111........1111....'],
    jump: ['....1111........1111....', '...12221........12221...', '...1111..........1111...', '........................', '........................'],
    skid: ['........111.....111.....', '.........121.....121....', '..........121.....121...', '..........1221....1221..', '..........1111....1111..'],
    pole1: ['.......111..111.........', '........121121..........', '.........1111...........', '.........1221...........', '.........1111...........'],
    pole2: ['........111..111........', '.........121121.........', '..........1111..........', '..........1221..........', '..........1111..........'],
  };
  for (const pose of Object.keys(bigLegs)) SP['hero_big_' + pose] = { l: heroL, r: bigBody.concat(bigLegs[pose]) };
  SP.hero_big_blink = { l: heroL, r: bigBlink.concat(bigLegs.idle) };

  // ---------------------------------------------------------------- the walker: a hex nut on two legs (16x16)
  const nut = [
    '...1........1...',
    '...1111111111...',
    '..122222222221..',
    '.12222222222221.',
    '.12233222233221.',
    '.12231222231221.',
    '.12222222222221.',
    '.12221111112221.',
    '.12222222222221.',
    '..122222222221..',
    '...1111111111...',
  ];
  const blank16 = '................';
  SP.foe_walker_1 = { l: foeL, r: [blank16, blank16].concat(nut, ['....11....11....', '...111....111...', blank16]) };
  SP.foe_walker_2 = { l: foeL, r: [blank16, blank16].concat(nut, ['.....11..11.....', '....111..111....', blank16]) };
  SP.foe_walker_flat = {
    l: foeL,
    r: [blank16, blank16, '....11111111....', '..122222222221..', '.12233222233221.', '.12222222222221.', '.11111111111111.', '..11........11..'],
  };

  // ---------------------------------------------------------------- the battery power-up (16x16, slots: SPAL.power / SPAL.life)
  SP.item_power = {
    l: R.slots(R.SPAL.power),
    r: [
      blank16,
      '......1111......',
      '......1331......',
      '....11111111....',
      '...1333333331...',
      '...1222222221...',
      '...1222112221...',
      '...1221111221...',
      '...1222112221...',
      '...1222222221...',
      '...1222222221...',
      '...1221111221...',
      '...1222222221...',
      '...1333333331...',
      '...1333333331...',
      '....11111111....',
    ],
  };

  // ---------------------------------------------------------------- coins: a chip with two sparkle marks (8x14)
  const coinFace = ['..kkkk..', '.kbbaak.', 'kbaaaaak', 'kbaakaak', 'kbakkkak', 'kbaakaak', 'kbaaaaak', 'kbaaaaak', 'kbaakaak', 'kbakkkak', 'kbaakaak', 'kbaaaaak', '.kaaaak.', '..kkkk..'];
  const coinNarrow = ['...kk...', '..kbak..'].concat(Array(10).fill('..kbak..'), ['..kaak..', '...kk...']);
  const coinEdge = ['...kk...'].concat(Array(12).fill('...ak...'), ['...kk...']);
  const coinSpin = [coinFace, coinNarrow, coinEdge, flipH(coinNarrow)];
  const coinL = { k: P.rust, a: P.gold, b: P.amber };
  const popL = { k: P.rust, a: P.amber, b: P.hudWhite };
  coinSpin.forEach((r, i) => {
    SP['item_coin_' + (i + 1)] = { l: coinL, r };
    SP['item_coinpop_' + (i + 1)] = { l: popL, r };
  });
  const hud = ['.kkk.', 'kbaak', 'kbaak', 'kbaak', 'kbaak', 'kbaak', 'kaaak', '.kkk.'];
  SP.item_hudcoin_1 = { l: coinL, r: hud };
  SP.item_hudcoin_2 = { l: { k: P.rust, a: P.amber, b: P.hudWhite }, r: hud };
  SP.item_hudcoin_3 = { l: { k: P.rust, a: P.clay, b: P.gold }, r: hud };

  // ---------------------------------------------------------------- the token: an eight-toothed gear, spinning (16x16)
  function gear(sx) {
    return shape(16, 16, (x, y) => {
      const dx = (x - 7.5) / sx, dy = y - 7.5;
      const r = Math.hypot(dx, dy);
      const a = Math.atan2(dy, dx);
      const tooth = Math.cos(a * 8) > 0.3;
      if (r < 2.2) return null; // the axle hole
      if (r < 3.4) return 'b';
      if (r < 5.6 || (tooth && r < 7.6)) return 'a';
      return null;
    }, 'k');
  }
  const tokenL = { k: P.ink, a: P.visor, b: P.hudWhite };
  const g1 = gear(1), g2 = gear(0.55);
  const g3 = gen(16, 16, (x, y) => (y < 1 || y > 14 ? null : x === 7 ? 'k' : x === 8 ? (y === 1 || y === 14 ? 'k' : 'a') : null));
  [g1, g2, g3, flipH(g2)].forEach((r, i) => (SP['item_token_' + (i + 1)] = { l: tokenL, r }));

  // ---------------------------------------------------------------- brick fragments (8x8, slots: SPAL.fragment / fragmentU)
  const frag = ['..111...', '.12221..', '1223221.', '1222221.', '.122211.', '..1211..', '...11...', '........'];
  SP.item_fragment_1 = { l: R.slots(R.SPAL.fragment), r: frag };
  SP.item_fragment_2 = { l: R.slots(R.SPAL.fragment), r: flipH(frag.slice().reverse()) };

  // ---------------------------------------------------------------- the checkpoint: a lamp post (16x32)
  const post = (lit) => {
    const top = ['.....kkkkkk.....', '....kbbbbbbk....', '....kbbbbbbk....', '....kbbbbbbk....', '.....kkkkkk.....'];
    if (lit) {
      top[0] = '..b..kkkkkk..b..';
      top[2] = '.b..kbbbbbbk..b.';
      top[4] = '..b..kkkkkk..b..';
    }
    const pole = Array(23).fill('......kaak......');
    pole[6] = '.....kaaaak.....';
    pole[7] = '.....kkkkkk.....';
    return top.concat(pole, ['.....kaaaak.....', '....kaaaaaak....', '...kaaaaaaaak...', '...kkkkkkkkkk...']);
  };
  SP.item_checkpoint_off = { l: { k: P.ink, a: P.steel, b: P.shadow }, r: post(false) };
  SP.item_checkpoint_on = { l: { k: P.ink, a: P.steel, b: P.lime }, r: post(true) };

  // ---------------------------------------------------------------- the goal: a radio beacon tower
  const lattice = ['......aaaa......', '......aa.a......', '......a.aa......', '......a..a......'];
  const towerL = { k: P.ink, a: P.steel, r: P.red };
  SP.goal_pole = { l: towerL, r: lattice.concat(lattice, lattice, lattice) };
  SP.goal_top = {
    l: towerL,
    r: ['.......kk.......', '......krrk......', '......krrk......', '.......kk.......', '.......aa.......', '.....aaaaaa.....'].concat(lattice.slice(3), lattice, lattice, lattice.slice(0, 1)),
  };
  // the banner that slides down the tower: a signal board with a bolt, its right edge on the mast
  SP.goal_flag = {
    l: { k: P.ink, a: P.clay, b: P.hudWhite },
    r: [
      blank16,
      '.kkkkkkkkkkkkkkk',
      '.kaaaaaaaaaaaaak',
      '.kaaaaaaabbaaaak',
      '.kaaaaaabbaaaaak',
      '.kaaaaabbbbbaaak',
      '.kaaaaaaabbaaaak',
      '.kaaaaaabbaaaaak',
      '.kaaaaabbaaaaaak',
      '.kaaaaaaaaaaaaak',
      '.kkkkkkkkkkkkkkk',
      blank16, blank16, blank16, blank16, blank16,
    ],
  };
  // the goal house: a tin radio hut with a vent the signal rises from (80x80; door x 33-46, vent at x 68)
  SP.goal_house = {
    l: { k: P.ink, a: P.clay, b: P.rust },
    r: gen(80, 80, (x, y) => {
      // the vent on the roof, at x 66..79, y 16..27
      if (x >= 66 && x <= 79 && y >= 16 && y <= 27) return x === 66 || x === 79 || y === 16 ? 'k' : y === 19 || y === 22 ? 'k' : 'b';
      // the roof: a shallow gable y 18..37
      if (y >= 18 && y <= 37) {
        const half = 22 + (y - 18) * 1.0;
        const x0 = Math.round(40 - half), x1 = Math.round(39 + half);
        if (x < x0 || x > x1) return null;
        if (x === x0 || x === x1 || y === 18 || y === 37) return 'k';
        return (y - 18) % 5 === 0 ? 'k' : 'b';
      }
      // the walls y 38..79, x 6..73
      if (y >= 38 && x >= 6 && x <= 73) {
        if (x === 6 || x === 73 || y === 79) return 'k';
        if (x >= 33 && x <= 46 && y >= 54) return 'k'; // the doorway
        if (x >= 32 && x <= 47 && y === 53) return 'b'; // the lintel
        if (x >= 14 && x <= 25 && y >= 44 && y <= 53) return x === 14 || x === 25 || y === 44 || y === 53 || x === 19 || x === 20 || y === 48 ? 'k' : 'b';
        if (x >= 54 && x <= 65 && y >= 44 && y <= 53) return x === 54 || x === 65 || y === 44 || y === 53 || x === 59 || x === 60 || y === 48 ? 'k' : 'b';
        return (x - 6) % 9 === 0 ? 'b' : 'a';
      }
      return null;
    }),
  };
  // the signal that rises from the vent: a diamond beacon (14x14)
  SP.goal_signal = {
    l: { k: P.ink, a: P.visor, b: P.hudWhite },
    r: shape(14, 14, (x, y) => {
      const d = Math.abs(x - 6.5) + Math.abs(y - 6.5);
      return d <= 3 ? 'b' : d <= 6.5 ? 'a' : null;
    }, 'k'),
  };
  // fireworks: a burst in three stages (16x16)
  const burst = (r0, r1, n, dots) =>
    gen(16, 16, (x, y) => {
      const dx = x - 7.5, dy = y - 7.5;
      const r = Math.hypot(dx, dy);
      const a = (Math.atan2(dy, dx) + Math.PI) / (2 * Math.PI);
      const spoke = Math.abs(a * n - Math.round(a * n)) < (dots ? 0.12 : 0.2);
      if (r < r0 || r > r1 || !spoke) return null;
      return r > r1 - 1.5 ? 'a' : r > (r0 + r1) / 2 ? 'b' : 'c';
    });
  const fwL = { a: P.hudWhite, b: P.gold, c: P.red };
  SP.goal_firework_1 = { l: fwL, r: burst(0, 3.2, 8, false) };
  SP.goal_firework_2 = { l: fwL, r: burst(1.5, 5.8, 8, false) };
  SP.goal_firework_3 = { l: fwL, r: burst(4, 7.8, 12, true) };

  // ---------------------------------------------------------------- tiles (16x16)
  // ground: a packed-earth block (soil with a lit top and left edge, a shaded bottom and right edge and a
  // few pebbles), so the two floor rows read as stacked earth rather than a repeated grass line
  SP.tile_ground = {
    l: { a: P.dirt, l: P.clay, g: P.rust },
    r: gen(16, 16, (x, y) => {
      if (y === 15 || x === 15) return 'g';
      if (y === 0 || x === 0) return 'l';
      const pebble = [[3, 4], [4, 4], [10, 3], [7, 9], [8, 9], [12, 11], [2, 12], [5, 13]];
      if (pebble.some(([px, py]) => px === x && py === y)) return 'g';
      if ((x === 4 && y === 3) || (x === 11 && y === 10)) return 'l';
      return 'a';
    }),
  };
  const brickRows = [
    'bbbbbbbbbbbbbbbb',
    'aaaaaaakaaaaaaak',
    'aaaaaaakaaaaaaak',
    'kkkkkkkkkkkkkkkk',
    'bbbbbbbbbbbbbbbb',
    'aaakaaaaaaakaaaa',
    'aaakaaaaaaakaaaa',
    'kkkkkkkkkkkkkkkk',
    'bbbbbbbbbbbbbbbb',
    'aaaaaaakaaaaaaak',
    'aaaaaaakaaaaaaak',
    'kkkkkkkkkkkkkkkk',
    'bbbbbbbbbbbbbbbb',
    'aaakaaaaaaakaaaa',
    'aaakaaaaaaakaaaa',
    'kkkkkkkkkkkkkkkk',
  ];
  SP.tile_brick = { l: { a: P.clay, b: P.amber, k: P.rust }, r: brickRows };
  // the ? block: a data crate with a bolt, shimmering through three palettes
  const crate = [
    'kkkkkkkkkkkkkkkk',
    'kbbbbbbbbbbbbbak',
    'kbkaaaaaaaaaakak',
    'kbaaaaaaakkaaaak',
    'kbaaaaaakkaaaaak',
    'kbaaaaakkaaaaaak',
    'kbaaaakkkkkkaaak',
    'kbaaaaaaaakkaaak',
    'kbaaaaaaakkaaaak',
    'kbaaaaaakkaaaaak',
    'kbaaaaakkaaaaaak',
    'kbaaaaakaaaaaaak',
    'kbaaaaaaaaaaaaak',
    'kbkaaaaaaaaaakak',
    'kaaaaaaaaaaaaaak',
    'kkkkkkkkkkkkkkkk',
  ];
  SP.tile_q_1 = { l: { k: P.ink, a: P.gold, b: P.amber }, r: crate };
  SP.tile_q_2 = { l: { k: P.ink, a: P.clay, b: P.gold }, r: crate };
  SP.tile_q_3 = { l: { k: P.ink, a: P.dirt, b: P.clay }, r: crate };
  const plate = gen(16, 16, (x, y) => {
    if (x === 0 || y === 0 || x === 15 || y === 15) return 'k';
    if ((x === 2 || x === 13) && (y === 2 || y === 13)) return 'k';
    return x === 1 || y === 1 ? 'b' : 'a';
  });
  SP.tile_used = { l: { k: P.ink, a: P.dirt, b: P.clay }, r: plate };
  SP.tile_stair = {
    l: { k: P.ink, a: P.shadow, b: P.steel },
    r: gen(16, 16, (x, y) => {
      if (x === 15 || y === 15) return 'k';
      if (x === 0 || y === 0) return 'b';
      if (x + y === 15 || x - y === 0) return 'b';
      return 'a';
    }),
  };
  SP.tile_ground_under = {
    l: { k: P.deep, a: P.teal, b: P.pale },
    r: gen(16, 16, (x, y) => {
      if (y === 0 || x === 0) return 'b';
      if (y === 15 || x === 15 || y === 7 || (y > 7 ? x === 4 : x === 11)) return 'k';
      return 'a';
    }),
  };
  SP.tile_brick_under = { l: { a: P.teal, b: P.pale, k: P.deep }, r: brickRows };

  // ---------------------------------------------------------------- conduit pipes (a vertical pair is 32 px wide)
  const pipeL = { k: P.ink, a: P.teal, b: P.pale };
  // the rim (x 0..31 across the pair, y 0..15) and the body (x 2..29) of a vertical conduit
  const rimAt = (x, y) => (x === 0 || x === 31 || y === 0 || y === 15 || y === 12 ? 'k' : x === 3 || x === 4 || x === 10 ? 'b' : y === 6 && x % 6 === 2 ? 'k' : 'a');
  const bodyAt = (x, y) => (x < 2 || x > 29 ? null : x === 2 || x === 29 ? 'k' : x === 6 || x === 7 || x === 12 ? 'b' : y === 8 && x % 6 === 4 ? 'k' : x === 25 ? 'k' : 'a');
  const half = (fn, off) => gen(16, 16, (x, y) => fn(x + off, y));
  SP.tile_pipe_tl = { l: pipeL, r: half(rimAt, 0) };
  SP.tile_pipe_tr = { l: pipeL, r: half(rimAt, 16) };
  SP.tile_pipe_l = { l: pipeL, r: half(bodyAt, 0) };
  SP.tile_pipe_r = { l: pipeL, r: half(bodyAt, 16) };
  // sideways: the same conduit turned a quarter (the pair is 32 px tall; its mouth faces left)
  const tall = (fn, off) => gen(16, 16, (x, y) => fn(y + off, x));
  SP.tile_pipe_side_top = { l: pipeL, r: tall(rimAt, 0) };
  SP.tile_pipe_side_bottom = { l: pipeL, r: tall(rimAt, 16) };
  SP.tile_pipe_body_top = { l: pipeL, r: tall(bodyAt, 0) };
  SP.tile_pipe_body_bottom = { l: pipeL, r: tall(bodyAt, 16) };
  // the join: the vertical conduit's left column, opened on its left where the sideways one runs in
  const join = (off) =>
    gen(16, 16, (x, y) => {
      const yy = y + off;
      if (yy >= 3 && yy <= 28 && x <= 3) return bodyAt(yy, x);
      return bodyAt(x, yy);
    });
  SP.tile_pipe_join_top = { l: pipeL, r: join(0) };
  SP.tile_pipe_join_bottom = { l: pipeL, r: join(16) };

  // ---------------------------------------------------------------- scenery
  // clouds: flat-bottomed puffs, n bumps across w (24 tall)
  const cloud = (w, n) => ({
    l: { k: P.cloud, a: P.hudWhite },
    r: shape(w, 24, (x, y) => {
      if (y > 20) return null;
      if (y >= 12 && x >= 3 && x <= w - 4) return 'a';
      for (let i = 0; i < n; i++) {
        const cx = (w / (n + 1)) * (i + 1), cy = 11 - (i % 2) * 3;
        if (Math.hypot(x + 0.5 - cx, (y + 0.5 - cy) * 1.2) < 8.5) return 'a';
      }
      return Math.hypot(x + 0.5 - 6, y + 0.5 - 15) < 6 || Math.hypot(x + 0.5 - (w - 6), y + 0.5 - 15) < 6 ? 'a' : null;
    }, 'k'),
  });
  SP.scenery_cloud_1 = cloud(32, 1);
  SP.scenery_cloud_2 = cloud(48, 2);
  SP.scenery_cloud_3 = cloud(64, 3);
  // shrubs: square-cut hedges with a lit top row (16 tall)
  const shrub = (w) => ({
    l: { k: P.ink, a: P.moss, b: P.lime },
    r: shape(w, 16, (x, y) => {
      const seg = Math.floor(x / 16);
      const top = seg % 2 ? 4 : 1;
      if (y < top || x < 1 || x > w - 2) return null;
      return y === top + 1 || (y - top) % 5 === 3 && x % 4 === seg % 4 ? 'b' : 'a';
    }, 'k'),
  });
  SP.scenery_bush_1 = shrub(32);
  SP.scenery_bush_2 = shrub(48);
  SP.scenery_bush_3 = shrub(64);
  // hills: terraced mesas, flat tops and stepped sides
  const mesa = (w, h, steps) => ({
    l: { k: P.ink, a: P.mesa, b: P.mesaLit },
    r: shape(w, h, (x, y) => {
      const stepH = Math.floor(h / steps);
      const level = Math.min(steps - 1, Math.floor(y / stepH));
      const inset = (steps - 1 - level) * Math.floor(w / (2 * steps + 1));
      if (x < inset || x > w - 1 - inset) return null;
      return y % stepH === 1 ? 'b' : 'a';
    }, 'k'),
  });
  SP.scenery_hill_small = mesa(48, 19, 2);
  SP.scenery_hill_big = mesa(80, 35, 3);
})();
